# -*- coding: utf-8 -*-
"""Pro C130 Project Data_cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M1suQuj-xDW0nm-3uN5h88_YH4c6VjcL
"""

import pandas as pd
import csv

df = pd.read_csv('total_stars.csv')
df

df.columns

df.drop(['Unnamed: 0','Unnamed: 6', 'Star_name.1', 'Distance.1', 'Mass.1', 'Radius.1','Luminosity'],axis=1,inplace=True)

df

final_data = df.dropna()
final_data

final_data.reset_index(drop=True,inplace = True)
final_data

final_data.to_csv('final_data.csv')

final_data.info()

final_data.describe()

final_data.head(5)

final_data.dtypes

